// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using back_test_project.Data;

#nullable disable

namespace back_test_project.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251014122607_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("back_test_project.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentName")
                        .IsUnique();

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentName = "Engineering"
                        },
                        new
                        {
                            Id = 2,
                            DepartmentName = "HR"
                        },
                        new
                        {
                            Id = 3,
                            DepartmentName = "Finance"
                        },
                        new
                        {
                            Id = 4,
                            DepartmentName = "Marketing"
                        },
                        new
                        {
                            Id = 5,
                            DepartmentName = "Sales"
                        });
                });

            modelBuilder.Entity("back_test_project.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("int");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("ManagerId");

                    b.ToTable("Employees", t =>
                        {
                            t.HasCheckConstraint("CK_Employee_Manager_Not_Self", "[ManagerId] IS NULL OR [ManagerId] <> [Id]");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentId = 1,
                            FirstName = "Mark",
                            LastName = "Twain",
                            Salary = 3000m
                        },
                        new
                        {
                            Id = 2,
                            DepartmentId = 1,
                            FirstName = "Ernest",
                            LastName = "Hemingway",
                            ManagerId = 1,
                            Salary = 3500m
                        },
                        new
                        {
                            Id = 3,
                            DepartmentId = 2,
                            FirstName = "Harper",
                            LastName = "Lee",
                            ManagerId = 1,
                            Salary = 2000m
                        },
                        new
                        {
                            Id = 4,
                            DepartmentId = 2,
                            FirstName = "F. Scott",
                            LastName = "Fitzgerald",
                            ManagerId = 3,
                            Salary = 2700m
                        },
                        new
                        {
                            Id = 5,
                            DepartmentId = 3,
                            FirstName = "John",
                            LastName = "Steinbeck",
                            ManagerId = 1,
                            Salary = 4500m
                        },
                        new
                        {
                            Id = 6,
                            DepartmentId = 3,
                            FirstName = "Toni",
                            LastName = "Morrison",
                            ManagerId = 5,
                            Salary = 3200m
                        },
                        new
                        {
                            Id = 7,
                            DepartmentId = 4,
                            FirstName = "Stephen",
                            LastName = "King",
                            Salary = 3800m
                        },
                        new
                        {
                            Id = 8,
                            DepartmentId = 4,
                            FirstName = "Jack",
                            LastName = "London",
                            ManagerId = 7,
                            Salary = 2100m
                        },
                        new
                        {
                            Id = 9,
                            DepartmentId = 5,
                            FirstName = "Edgar",
                            LastName = "Poe",
                            Salary = 3700m
                        },
                        new
                        {
                            Id = 10,
                            DepartmentId = 5,
                            FirstName = "Walt",
                            LastName = "Whitman",
                            ManagerId = 9,
                            Salary = 3050m
                        });
                });

            modelBuilder.Entity("back_test_project.Models.Employee", b =>
                {
                    b.HasOne("back_test_project.Models.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("back_test_project.Models.Employee", "Manager")
                        .WithMany("Subordinates")
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Department");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("back_test_project.Models.Department", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("back_test_project.Models.Employee", b =>
                {
                    b.Navigation("Subordinates");
                });
#pragma warning restore 612, 618
        }
    }
}
