// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using back_test_project.Data;

#nullable disable

namespace back_test_project.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("back_test_project.Models.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentName")
                        .IsUnique();

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentName = "Engineering"
                        },
                        new
                        {
                            Id = 2,
                            DepartmentName = "HR"
                        },
                        new
                        {
                            Id = 3,
                            DepartmentName = "Finance"
                        },
                        new
                        {
                            Id = 4,
                            DepartmentName = "Marketing"
                        },
                        new
                        {
                            Id = 5,
                            DepartmentName = "Sales"
                        });
                });

            modelBuilder.Entity("back_test_project.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("integer");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Salary")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("ManagerId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentId = 1,
                            FirstName = "Mark",
                            LastName = "Twain",
                            Salary = 3000m
                        },
                        new
                        {
                            Id = 2,
                            DepartmentId = 1,
                            FirstName = "Ernest",
                            LastName = "Hemingway",
                            ManagerId = 1,
                            Salary = 3500m
                        },
                        new
                        {
                            Id = 3,
                            DepartmentId = 2,
                            FirstName = "Harper",
                            LastName = "Lee",
                            ManagerId = 1,
                            Salary = 2000m
                        },
                        new
                        {
                            Id = 4,
                            DepartmentId = 2,
                            FirstName = "F. Scott",
                            LastName = "Fitzgerald",
                            ManagerId = 3,
                            Salary = 2700m
                        },
                        new
                        {
                            Id = 5,
                            DepartmentId = 3,
                            FirstName = "John",
                            LastName = "Steinbeck",
                            ManagerId = 1,
                            Salary = 4500m
                        },
                        new
                        {
                            Id = 6,
                            DepartmentId = 3,
                            FirstName = "Toni",
                            LastName = "Morrison",
                            ManagerId = 5,
                            Salary = 3200m
                        },
                        new
                        {
                            Id = 7,
                            DepartmentId = 4,
                            FirstName = "Stephen",
                            LastName = "King",
                            Salary = 3800m
                        },
                        new
                        {
                            Id = 8,
                            DepartmentId = 4,
                            FirstName = "Jack",
                            LastName = "London",
                            ManagerId = 7,
                            Salary = 2100m
                        },
                        new
                        {
                            Id = 9,
                            DepartmentId = 5,
                            FirstName = "Edgar",
                            LastName = "Poe",
                            Salary = 3700m
                        },
                        new
                        {
                            Id = 10,
                            DepartmentId = 5,
                            FirstName = "Walt",
                            LastName = "Whitman",
                            ManagerId = 9,
                            Salary = 3050m
                        },
                        new
                        {
                            Id = 11,
                            DepartmentId = 1,
                            FirstName = "Tom",
                            LastName = "Hanks",
                            ManagerId = 1,
                            Salary = 5200m
                        },
                        new
                        {
                            Id = 12,
                            DepartmentId = 1,
                            FirstName = "Meryl",
                            LastName = "Streep",
                            ManagerId = 1,
                            Salary = 5400m
                        },
                        new
                        {
                            Id = 13,
                            DepartmentId = 1,
                            FirstName = "Denzel",
                            LastName = "Washington",
                            ManagerId = 5,
                            Salary = 5600m
                        },
                        new
                        {
                            Id = 14,
                            DepartmentId = 1,
                            FirstName = "Leonardo",
                            LastName = "DiCaprio",
                            ManagerId = 7,
                            Salary = 5500m
                        },
                        new
                        {
                            Id = 15,
                            DepartmentId = 1,
                            FirstName = "Brad",
                            LastName = "Pitt",
                            ManagerId = 9,
                            Salary = 5300m
                        },
                        new
                        {
                            Id = 16,
                            DepartmentId = 1,
                            FirstName = "Angelina",
                            LastName = "Jolie",
                            ManagerId = 1,
                            Salary = 5200m
                        },
                        new
                        {
                            Id = 17,
                            DepartmentId = 1,
                            FirstName = "Robert",
                            LastName = "DeNiro",
                            ManagerId = 5,
                            Salary = 5700m
                        },
                        new
                        {
                            Id = 18,
                            DepartmentId = 1,
                            FirstName = "Al",
                            LastName = "Pacino",
                            ManagerId = 7,
                            Salary = 5600m
                        },
                        new
                        {
                            Id = 19,
                            DepartmentId = 1,
                            FirstName = "Morgan",
                            LastName = "Freeman",
                            ManagerId = 9,
                            Salary = 5800m
                        },
                        new
                        {
                            Id = 20,
                            DepartmentId = 1,
                            FirstName = "Samuel",
                            LastName = "Jackson",
                            ManagerId = 1,
                            Salary = 5200m
                        },
                        new
                        {
                            Id = 21,
                            DepartmentId = 1,
                            FirstName = "Scarlett",
                            LastName = "Johansson",
                            ManagerId = 5,
                            Salary = 5100m
                        },
                        new
                        {
                            Id = 22,
                            DepartmentId = 1,
                            FirstName = "Chris",
                            LastName = "Evans",
                            ManagerId = 7,
                            Salary = 4900m
                        },
                        new
                        {
                            Id = 23,
                            DepartmentId = 1,
                            FirstName = "Chris",
                            LastName = "Hemsworth",
                            ManagerId = 9,
                            Salary = 5000m
                        },
                        new
                        {
                            Id = 24,
                            DepartmentId = 1,
                            FirstName = "Robert",
                            LastName = "Downey",
                            ManagerId = 1,
                            Salary = 5800m
                        },
                        new
                        {
                            Id = 25,
                            DepartmentId = 1,
                            FirstName = "Jennifer",
                            LastName = "Lawrence",
                            ManagerId = 5,
                            Salary = 5050m
                        },
                        new
                        {
                            Id = 26,
                            DepartmentId = 1,
                            FirstName = "Natalie",
                            LastName = "Portman",
                            ManagerId = 7,
                            Salary = 5150m
                        },
                        new
                        {
                            Id = 27,
                            DepartmentId = 1,
                            FirstName = "Matt",
                            LastName = "Damon",
                            ManagerId = 9,
                            Salary = 5200m
                        },
                        new
                        {
                            Id = 28,
                            DepartmentId = 1,
                            FirstName = "Ben",
                            LastName = "Affleck",
                            ManagerId = 1,
                            Salary = 4900m
                        },
                        new
                        {
                            Id = 29,
                            DepartmentId = 1,
                            FirstName = "Keanu",
                            LastName = "Reeves",
                            ManagerId = 5,
                            Salary = 5400m
                        },
                        new
                        {
                            Id = 30,
                            DepartmentId = 1,
                            FirstName = "Harrison",
                            LastName = "Ford",
                            ManagerId = 7,
                            Salary = 5500m
                        },
                        new
                        {
                            Id = 31,
                            DepartmentId = 1,
                            FirstName = "Julia",
                            LastName = "Roberts",
                            ManagerId = 9,
                            Salary = 5100m
                        },
                        new
                        {
                            Id = 32,
                            DepartmentId = 1,
                            FirstName = "Sandra",
                            LastName = "Bullock",
                            ManagerId = 1,
                            Salary = 5050m
                        },
                        new
                        {
                            Id = 33,
                            DepartmentId = 1,
                            FirstName = "Anne",
                            LastName = "Hathaway",
                            ManagerId = 5,
                            Salary = 4950m
                        },
                        new
                        {
                            Id = 34,
                            DepartmentId = 1,
                            FirstName = "Emma",
                            LastName = "Stone",
                            ManagerId = 7,
                            Salary = 4800m
                        },
                        new
                        {
                            Id = 35,
                            DepartmentId = 1,
                            FirstName = "Ryan",
                            LastName = "Gosling",
                            ManagerId = 9,
                            Salary = 4850m
                        },
                        new
                        {
                            Id = 36,
                            DepartmentId = 1,
                            FirstName = "Christian",
                            LastName = "Bale",
                            ManagerId = 1,
                            Salary = 5400m
                        },
                        new
                        {
                            Id = 37,
                            DepartmentId = 1,
                            FirstName = "Hugh",
                            LastName = "Jackman",
                            ManagerId = 5,
                            Salary = 5350m
                        },
                        new
                        {
                            Id = 38,
                            DepartmentId = 1,
                            FirstName = "Will",
                            LastName = "Smith",
                            ManagerId = 7,
                            Salary = 5200m
                        },
                        new
                        {
                            Id = 39,
                            DepartmentId = 1,
                            FirstName = "Joaquin",
                            LastName = "Phoenix",
                            ManagerId = 9,
                            Salary = 5450m
                        },
                        new
                        {
                            Id = 40,
                            DepartmentId = 1,
                            FirstName = "Rami",
                            LastName = "Malek",
                            ManagerId = 1,
                            Salary = 4700m
                        },
                        new
                        {
                            Id = 41,
                            DepartmentId = 1,
                            FirstName = "Bryan",
                            LastName = "Cranston",
                            ManagerId = 5,
                            Salary = 5000m
                        },
                        new
                        {
                            Id = 42,
                            DepartmentId = 1,
                            FirstName = "Aaron",
                            LastName = "Paul",
                            ManagerId = 7,
                            Salary = 4550m
                        },
                        new
                        {
                            Id = 43,
                            DepartmentId = 1,
                            FirstName = "Zoe",
                            LastName = "Saldana",
                            ManagerId = 9,
                            Salary = 4700m
                        },
                        new
                        {
                            Id = 44,
                            DepartmentId = 1,
                            FirstName = "Amy",
                            LastName = "Adams",
                            ManagerId = 1,
                            Salary = 5100m
                        },
                        new
                        {
                            Id = 45,
                            DepartmentId = 1,
                            FirstName = "Viola",
                            LastName = "Davis",
                            ManagerId = 5,
                            Salary = 5200m
                        },
                        new
                        {
                            Id = 46,
                            DepartmentId = 1,
                            FirstName = "Octavia",
                            LastName = "Spencer",
                            ManagerId = 7,
                            Salary = 4800m
                        },
                        new
                        {
                            Id = 47,
                            DepartmentId = 1,
                            FirstName = "Melissa",
                            LastName = "McCarthy",
                            ManagerId = 9,
                            Salary = 4500m
                        },
                        new
                        {
                            Id = 48,
                            DepartmentId = 1,
                            FirstName = "Steve",
                            LastName = "Carell",
                            ManagerId = 1,
                            Salary = 4600m
                        },
                        new
                        {
                            Id = 49,
                            DepartmentId = 1,
                            FirstName = "Jim",
                            LastName = "Carrey",
                            ManagerId = 5,
                            Salary = 5000m
                        },
                        new
                        {
                            Id = 50,
                            DepartmentId = 1,
                            FirstName = "Eddie",
                            LastName = "Murphy",
                            ManagerId = 7,
                            Salary = 5200m
                        },
                        new
                        {
                            Id = 51,
                            DepartmentId = 1,
                            FirstName = "Chris",
                            LastName = "Pratt",
                            ManagerId = 9,
                            Salary = 4800m
                        },
                        new
                        {
                            Id = 52,
                            DepartmentId = 1,
                            FirstName = "Zachary",
                            LastName = "Levi",
                            ManagerId = 1,
                            Salary = 4550m
                        },
                        new
                        {
                            Id = 53,
                            DepartmentId = 1,
                            FirstName = "Gal",
                            LastName = "Gadot",
                            ManagerId = 5,
                            Salary = 5050m
                        },
                        new
                        {
                            Id = 54,
                            DepartmentId = 1,
                            FirstName = "Brie",
                            LastName = "Larson",
                            ManagerId = 7,
                            Salary = 4950m
                        },
                        new
                        {
                            Id = 55,
                            DepartmentId = 1,
                            FirstName = "Jason",
                            LastName = "Momoa",
                            ManagerId = 9,
                            Salary = 5000m
                        },
                        new
                        {
                            Id = 56,
                            DepartmentId = 1,
                            FirstName = "Mark",
                            LastName = "Ruffalo",
                            ManagerId = 1,
                            Salary = 5150m
                        },
                        new
                        {
                            Id = 57,
                            DepartmentId = 1,
                            FirstName = "Jeremy",
                            LastName = "Renner",
                            ManagerId = 5,
                            Salary = 4700m
                        },
                        new
                        {
                            Id = 58,
                            DepartmentId = 1,
                            FirstName = "Paul",
                            LastName = "Rudd",
                            ManagerId = 7,
                            Salary = 4800m
                        },
                        new
                        {
                            Id = 59,
                            DepartmentId = 1,
                            FirstName = "Chadwick",
                            LastName = "Boseman",
                            ManagerId = 9,
                            Salary = 5400m
                        },
                        new
                        {
                            Id = 60,
                            DepartmentId = 1,
                            FirstName = "Michael",
                            LastName = "Keaton",
                            ManagerId = 1,
                            Salary = 5100m
                        },
                        new
                        {
                            Id = 61,
                            DepartmentId = 1,
                            FirstName = "Tom",
                            LastName = "Cruise",
                            ManagerId = 5,
                            Salary = 5600m
                        },
                        new
                        {
                            Id = 62,
                            DepartmentId = 1,
                            FirstName = "Nicolas",
                            LastName = "Cage",
                            ManagerId = 7,
                            Salary = 5000m
                        },
                        new
                        {
                            Id = 63,
                            DepartmentId = 1,
                            FirstName = "Keegan-Michael",
                            LastName = "Key",
                            ManagerId = 9,
                            Salary = 4500m
                        },
                        new
                        {
                            Id = 64,
                            DepartmentId = 1,
                            FirstName = "Jordan",
                            LastName = "Peele",
                            ManagerId = 1,
                            Salary = 5200m
                        },
                        new
                        {
                            Id = 65,
                            DepartmentId = 1,
                            FirstName = "Kerry",
                            LastName = "Washington",
                            ManagerId = 5,
                            Salary = 4950m
                        },
                        new
                        {
                            Id = 66,
                            DepartmentId = 1,
                            FirstName = "Ethan",
                            LastName = "Hawke",
                            ManagerId = 7,
                            Salary = 4800m
                        },
                        new
                        {
                            Id = 67,
                            DepartmentId = 1,
                            FirstName = "Jodie",
                            LastName = "Foster",
                            ManagerId = 9,
                            Salary = 5300m
                        },
                        new
                        {
                            Id = 68,
                            DepartmentId = 1,
                            FirstName = "Sigourney",
                            LastName = "Weaver",
                            ManagerId = 1,
                            Salary = 5200m
                        },
                        new
                        {
                            Id = 69,
                            DepartmentId = 1,
                            FirstName = "Uma",
                            LastName = "Thurman",
                            ManagerId = 5,
                            Salary = 4850m
                        },
                        new
                        {
                            Id = 70,
                            DepartmentId = 1,
                            FirstName = "Winona",
                            LastName = "Ryder",
                            ManagerId = 7,
                            Salary = 4700m
                        },
                        new
                        {
                            Id = 71,
                            DepartmentId = 2,
                            FirstName = "Michael",
                            LastName = "Jordan",
                            ManagerId = 9,
                            Salary = 6000m
                        },
                        new
                        {
                            Id = 72,
                            DepartmentId = 2,
                            FirstName = "Serena",
                            LastName = "Williams",
                            ManagerId = 5,
                            Salary = 5900m
                        },
                        new
                        {
                            Id = 73,
                            DepartmentId = 2,
                            FirstName = "Tiger",
                            LastName = "Woods",
                            ManagerId = 7,
                            Salary = 5800m
                        },
                        new
                        {
                            Id = 74,
                            DepartmentId = 2,
                            FirstName = "LeBron",
                            LastName = "James",
                            ManagerId = 1,
                            Salary = 5900m
                        },
                        new
                        {
                            Id = 75,
                            DepartmentId = 2,
                            FirstName = "Kobe",
                            LastName = "Bryant",
                            ManagerId = 9,
                            Salary = 6000m
                        },
                        new
                        {
                            Id = 76,
                            DepartmentId = 2,
                            FirstName = "Shaquille",
                            LastName = "ONeal",
                            ManagerId = 5,
                            Salary = 5700m
                        },
                        new
                        {
                            Id = 77,
                            DepartmentId = 2,
                            FirstName = "Tom",
                            LastName = "Brady",
                            ManagerId = 7,
                            Salary = 5800m
                        },
                        new
                        {
                            Id = 78,
                            DepartmentId = 2,
                            FirstName = "Peyton",
                            LastName = "Manning",
                            ManagerId = 1,
                            Salary = 5600m
                        },
                        new
                        {
                            Id = 79,
                            DepartmentId = 2,
                            FirstName = "Joe",
                            LastName = "Montana",
                            ManagerId = 9,
                            Salary = 5500m
                        },
                        new
                        {
                            Id = 80,
                            DepartmentId = 2,
                            FirstName = "Mia",
                            LastName = "Hamm",
                            ManagerId = 5,
                            Salary = 5200m
                        },
                        new
                        {
                            Id = 81,
                            DepartmentId = 2,
                            FirstName = "Alex",
                            LastName = "Morgan",
                            ManagerId = 7,
                            Salary = 5200m
                        },
                        new
                        {
                            Id = 82,
                            DepartmentId = 2,
                            FirstName = "Simone",
                            LastName = "Biles",
                            ManagerId = 1,
                            Salary = 5400m
                        },
                        new
                        {
                            Id = 83,
                            DepartmentId = 2,
                            FirstName = "Michael",
                            LastName = "Phelps",
                            ManagerId = 9,
                            Salary = 5600m
                        },
                        new
                        {
                            Id = 84,
                            DepartmentId = 2,
                            FirstName = "Lindsey",
                            LastName = "Vonn",
                            ManagerId = 5,
                            Salary = 5200m
                        },
                        new
                        {
                            Id = 85,
                            DepartmentId = 2,
                            FirstName = "Billie",
                            LastName = "Jean",
                            ManagerId = 7,
                            Salary = 5100m
                        },
                        new
                        {
                            Id = 86,
                            DepartmentId = 2,
                            FirstName = "Venus",
                            LastName = "Williams",
                            ManagerId = 1,
                            Salary = 5450m
                        },
                        new
                        {
                            Id = 87,
                            DepartmentId = 2,
                            FirstName = "Larry",
                            LastName = "Bird",
                            ManagerId = 9,
                            Salary = 5600m
                        },
                        new
                        {
                            Id = 88,
                            DepartmentId = 2,
                            FirstName = "Magic",
                            LastName = "Johnson",
                            ManagerId = 5,
                            Salary = 5800m
                        },
                        new
                        {
                            Id = 89,
                            DepartmentId = 2,
                            FirstName = "Kareem",
                            LastName = "AbdulJabbar",
                            ManagerId = 7,
                            Salary = 5900m
                        },
                        new
                        {
                            Id = 90,
                            DepartmentId = 2,
                            FirstName = "Charles",
                            LastName = "Barkley",
                            ManagerId = 1,
                            Salary = 5300m
                        },
                        new
                        {
                            Id = 91,
                            DepartmentId = 2,
                            FirstName = "Allen",
                            LastName = "Iverson",
                            ManagerId = 9,
                            Salary = 5200m
                        },
                        new
                        {
                            Id = 92,
                            DepartmentId = 2,
                            FirstName = "Steph",
                            LastName = "Curry",
                            ManagerId = 5,
                            Salary = 5850m
                        },
                        new
                        {
                            Id = 93,
                            DepartmentId = 2,
                            FirstName = "Kevin",
                            LastName = "Durant",
                            ManagerId = 7,
                            Salary = 5750m
                        },
                        new
                        {
                            Id = 94,
                            DepartmentId = 2,
                            FirstName = "James",
                            LastName = "Harden",
                            ManagerId = 1,
                            Salary = 5650m
                        },
                        new
                        {
                            Id = 95,
                            DepartmentId = 2,
                            FirstName = "Kawhi",
                            LastName = "Leonard",
                            ManagerId = 9,
                            Salary = 5500m
                        },
                        new
                        {
                            Id = 96,
                            DepartmentId = 2,
                            FirstName = "Giannis",
                            LastName = "Antetokounmpo",
                            ManagerId = 5,
                            Salary = 5600m
                        },
                        new
                        {
                            Id = 97,
                            DepartmentId = 2,
                            FirstName = "Damian",
                            LastName = "Lillard",
                            ManagerId = 7,
                            Salary = 5400m
                        },
                        new
                        {
                            Id = 98,
                            DepartmentId = 2,
                            FirstName = "Russell",
                            LastName = "Westbrook",
                            ManagerId = 1,
                            Salary = 5450m
                        },
                        new
                        {
                            Id = 99,
                            DepartmentId = 2,
                            FirstName = "Carmelo",
                            LastName = "Anthony",
                            ManagerId = 9,
                            Salary = 5350m
                        },
                        new
                        {
                            Id = 100,
                            DepartmentId = 2,
                            FirstName = "Dirk",
                            LastName = "Nowitzki",
                            ManagerId = 5,
                            Salary = 5700m
                        },
                        new
                        {
                            Id = 101,
                            DepartmentId = 3,
                            FirstName = "Ernest",
                            LastName = "Hemingway",
                            ManagerId = 1,
                            Salary = 5200m
                        },
                        new
                        {
                            Id = 102,
                            DepartmentId = 3,
                            FirstName = "William",
                            LastName = "Faulkner",
                            ManagerId = 5,
                            Salary = 5100m
                        },
                        new
                        {
                            Id = 103,
                            DepartmentId = 3,
                            FirstName = "Ray",
                            LastName = "Bradbury",
                            ManagerId = 7,
                            Salary = 5000m
                        },
                        new
                        {
                            Id = 104,
                            DepartmentId = 3,
                            FirstName = "Kurt",
                            LastName = "Vonnegut",
                            ManagerId = 9,
                            Salary = 4950m
                        },
                        new
                        {
                            Id = 105,
                            DepartmentId = 3,
                            FirstName = "George",
                            LastName = "Martin",
                            ManagerId = 1,
                            Salary = 5300m
                        },
                        new
                        {
                            Id = 106,
                            DepartmentId = 3,
                            FirstName = "Isaac",
                            LastName = "Asimov",
                            ManagerId = 5,
                            Salary = 5400m
                        },
                        new
                        {
                            Id = 107,
                            DepartmentId = 3,
                            FirstName = "Philip",
                            LastName = "Dick",
                            ManagerId = 7,
                            Salary = 5050m
                        },
                        new
                        {
                            Id = 108,
                            DepartmentId = 3,
                            FirstName = "Ursula",
                            LastName = "LeGuin",
                            ManagerId = 9,
                            Salary = 5200m
                        },
                        new
                        {
                            Id = 109,
                            DepartmentId = 3,
                            FirstName = "James",
                            LastName = "Baldwin",
                            ManagerId = 1,
                            Salary = 5100m
                        },
                        new
                        {
                            Id = 110,
                            DepartmentId = 3,
                            FirstName = "Ralph",
                            LastName = "Ellison",
                            ManagerId = 5,
                            Salary = 4950m
                        },
                        new
                        {
                            Id = 111,
                            DepartmentId = 3,
                            FirstName = "Truman",
                            LastName = "Capote",
                            ManagerId = 7,
                            Salary = 5000m
                        },
                        new
                        {
                            Id = 112,
                            DepartmentId = 3,
                            FirstName = "JD",
                            LastName = "Salinger",
                            ManagerId = 9,
                            Salary = 5050m
                        },
                        new
                        {
                            Id = 113,
                            DepartmentId = 3,
                            FirstName = "Thomas",
                            LastName = "Pynchon",
                            ManagerId = 1,
                            Salary = 5300m
                        },
                        new
                        {
                            Id = 114,
                            DepartmentId = 3,
                            FirstName = "Don",
                            LastName = "DeLillo",
                            ManagerId = 5,
                            Salary = 5200m
                        },
                        new
                        {
                            Id = 115,
                            DepartmentId = 3,
                            FirstName = "Cormac",
                            LastName = "McCarthy",
                            ManagerId = 7,
                            Salary = 5400m
                        },
                        new
                        {
                            Id = 116,
                            DepartmentId = 3,
                            FirstName = "Jonathan",
                            LastName = "Franzen",
                            ManagerId = 9,
                            Salary = 4850m
                        },
                        new
                        {
                            Id = 117,
                            DepartmentId = 3,
                            FirstName = "Zadie",
                            LastName = "Smith",
                            ManagerId = 1,
                            Salary = 4800m
                        },
                        new
                        {
                            Id = 118,
                            DepartmentId = 3,
                            FirstName = "Donna",
                            LastName = "Tartt",
                            ManagerId = 5,
                            Salary = 4900m
                        },
                        new
                        {
                            Id = 119,
                            DepartmentId = 3,
                            FirstName = "Colson",
                            LastName = "Whitehead",
                            ManagerId = 7,
                            Salary = 4950m
                        },
                        new
                        {
                            Id = 120,
                            DepartmentId = 3,
                            FirstName = "Jhumpa",
                            LastName = "Lahiri",
                            ManagerId = 9,
                            Salary = 4750m
                        },
                        new
                        {
                            Id = 121,
                            DepartmentId = 3,
                            FirstName = "Stephen",
                            LastName = "Curry",
                            ManagerId = 1,
                            Salary = 4600m
                        },
                        new
                        {
                            Id = 122,
                            DepartmentId = 3,
                            FirstName = "Serena",
                            LastName = "Williams",
                            ManagerId = 5,
                            Salary = 4700m
                        },
                        new
                        {
                            Id = 123,
                            DepartmentId = 3,
                            FirstName = "Maya",
                            LastName = "Angelou",
                            ManagerId = 7,
                            Salary = 5100m
                        },
                        new
                        {
                            Id = 124,
                            DepartmentId = 3,
                            FirstName = "Tennessee",
                            LastName = "Williams",
                            ManagerId = 9,
                            Salary = 5200m
                        },
                        new
                        {
                            Id = 125,
                            DepartmentId = 3,
                            FirstName = "Arthur",
                            LastName = "Miller",
                            ManagerId = 1,
                            Salary = 5050m
                        },
                        new
                        {
                            Id = 126,
                            DepartmentId = 3,
                            FirstName = "Tony",
                            LastName = "Morrison",
                            ManagerId = 5,
                            Salary = 4950m
                        },
                        new
                        {
                            Id = 127,
                            DepartmentId = 3,
                            FirstName = "Alice",
                            LastName = "Walker",
                            ManagerId = 7,
                            Salary = 4900m
                        },
                        new
                        {
                            Id = 128,
                            DepartmentId = 3,
                            FirstName = "Amy",
                            LastName = "Tan",
                            ManagerId = 9,
                            Salary = 4700m
                        },
                        new
                        {
                            Id = 129,
                            DepartmentId = 3,
                            FirstName = "Neil",
                            LastName = "Gaiman",
                            ManagerId = 1,
                            Salary = 5200m
                        },
                        new
                        {
                            Id = 130,
                            DepartmentId = 3,
                            FirstName = "Suzanne",
                            LastName = "Collins",
                            ManagerId = 5,
                            Salary = 4750m
                        },
                        new
                        {
                            Id = 131,
                            DepartmentId = 3,
                            FirstName = "Michael",
                            LastName = "Chabon",
                            ManagerId = 7,
                            Salary = 4850m
                        },
                        new
                        {
                            Id = 132,
                            DepartmentId = 3,
                            FirstName = "Harlan",
                            LastName = "Ellison",
                            ManagerId = 9,
                            Salary = 4950m
                        },
                        new
                        {
                            Id = 133,
                            DepartmentId = 3,
                            FirstName = "Anne",
                            LastName = "Tyler",
                            ManagerId = 1,
                            Salary = 4650m
                        },
                        new
                        {
                            Id = 134,
                            DepartmentId = 3,
                            FirstName = "Donna",
                            LastName = "Haraway",
                            ManagerId = 5,
                            Salary = 4700m
                        },
                        new
                        {
                            Id = 135,
                            DepartmentId = 3,
                            FirstName = "TaNehisi",
                            LastName = "Coates",
                            ManagerId = 7,
                            Salary = 4800m
                        },
                        new
                        {
                            Id = 136,
                            DepartmentId = 3,
                            FirstName = "Roxane",
                            LastName = "Gay",
                            ManagerId = 9,
                            Salary = 4600m
                        },
                        new
                        {
                            Id = 137,
                            DepartmentId = 3,
                            FirstName = "Walter",
                            LastName = "Mosley",
                            ManagerId = 1,
                            Salary = 5000m
                        },
                        new
                        {
                            Id = 138,
                            DepartmentId = 3,
                            FirstName = "Michael",
                            LastName = "Lewis",
                            ManagerId = 5,
                            Salary = 5450m
                        },
                        new
                        {
                            Id = 139,
                            DepartmentId = 3,
                            FirstName = "Nassim",
                            LastName = "Taleb",
                            ManagerId = 7,
                            Salary = 5400m
                        },
                        new
                        {
                            Id = 140,
                            DepartmentId = 3,
                            FirstName = "Steven",
                            LastName = "Levitt",
                            ManagerId = 9,
                            Salary = 5350m
                        },
                        new
                        {
                            Id = 141,
                            DepartmentId = 4,
                            FirstName = "Clint",
                            LastName = "Eastwood",
                            ManagerId = 7,
                            Salary = 5600m
                        },
                        new
                        {
                            Id = 142,
                            DepartmentId = 4,
                            FirstName = "Quentin",
                            LastName = "Tarantino",
                            ManagerId = 1,
                            Salary = 5500m
                        },
                        new
                        {
                            Id = 143,
                            DepartmentId = 4,
                            FirstName = "Christopher",
                            LastName = "Nolan",
                            ManagerId = 5,
                            Salary = 5700m
                        },
                        new
                        {
                            Id = 144,
                            DepartmentId = 4,
                            FirstName = "Martin",
                            LastName = "Scorsese",
                            ManagerId = 9,
                            Salary = 5800m
                        },
                        new
                        {
                            Id = 145,
                            DepartmentId = 4,
                            FirstName = "Spike",
                            LastName = "Lee",
                            ManagerId = 7,
                            Salary = 5200m
                        },
                        new
                        {
                            Id = 146,
                            DepartmentId = 4,
                            FirstName = "Greta",
                            LastName = "Gerwig",
                            ManagerId = 1,
                            Salary = 5150m
                        },
                        new
                        {
                            Id = 147,
                            DepartmentId = 4,
                            FirstName = "Ava",
                            LastName = "DuVernay",
                            ManagerId = 5,
                            Salary = 5100m
                        },
                        new
                        {
                            Id = 148,
                            DepartmentId = 4,
                            FirstName = "Sofia",
                            LastName = "Coppola",
                            ManagerId = 9,
                            Salary = 5050m
                        },
                        new
                        {
                            Id = 149,
                            DepartmentId = 4,
                            FirstName = "Wes",
                            LastName = "Anderson",
                            ManagerId = 7,
                            Salary = 5000m
                        },
                        new
                        {
                            Id = 150,
                            DepartmentId = 4,
                            FirstName = "David",
                            LastName = "Fincher",
                            ManagerId = 1,
                            Salary = 5450m
                        },
                        new
                        {
                            Id = 151,
                            DepartmentId = 4,
                            FirstName = "Ron",
                            LastName = "Howard",
                            ManagerId = 5,
                            Salary = 5200m
                        },
                        new
                        {
                            Id = 152,
                            DepartmentId = 4,
                            FirstName = "James",
                            LastName = "Cameron",
                            ManagerId = 9,
                            Salary = 5900m
                        },
                        new
                        {
                            Id = 153,
                            DepartmentId = 4,
                            FirstName = "JJ",
                            LastName = "Abrams",
                            ManagerId = 7,
                            Salary = 5300m
                        },
                        new
                        {
                            Id = 154,
                            DepartmentId = 4,
                            FirstName = "Ridley",
                            LastName = "Scott",
                            ManagerId = 1,
                            Salary = 5550m
                        },
                        new
                        {
                            Id = 155,
                            DepartmentId = 4,
                            FirstName = "Denis",
                            LastName = "Villeneuve",
                            ManagerId = 5,
                            Salary = 5600m
                        },
                        new
                        {
                            Id = 156,
                            DepartmentId = 4,
                            FirstName = "Jordan",
                            LastName = "Peele",
                            ManagerId = 9,
                            Salary = 5200m
                        },
                        new
                        {
                            Id = 157,
                            DepartmentId = 4,
                            FirstName = "Taika",
                            LastName = "Waititi",
                            ManagerId = 7,
                            Salary = 5150m
                        },
                        new
                        {
                            Id = 158,
                            DepartmentId = 4,
                            FirstName = "Patty",
                            LastName = "Jenkins",
                            ManagerId = 1,
                            Salary = 5100m
                        },
                        new
                        {
                            Id = 159,
                            DepartmentId = 4,
                            FirstName = "Catherine",
                            LastName = "Hardwicke",
                            ManagerId = 5,
                            Salary = 4850m
                        },
                        new
                        {
                            Id = 160,
                            DepartmentId = 4,
                            FirstName = "Ryan",
                            LastName = "Coogler",
                            ManagerId = 9,
                            Salary = 5250m
                        },
                        new
                        {
                            Id = 161,
                            DepartmentId = 4,
                            FirstName = "Jon",
                            LastName = "Favreau",
                            ManagerId = 7,
                            Salary = 5350m
                        },
                        new
                        {
                            Id = 162,
                            DepartmentId = 4,
                            FirstName = "Barry",
                            LastName = "Jenkins",
                            ManagerId = 1,
                            Salary = 5200m
                        },
                        new
                        {
                            Id = 163,
                            DepartmentId = 4,
                            FirstName = "Seth",
                            LastName = "MacFarlane",
                            ManagerId = 5,
                            Salary = 5000m
                        },
                        new
                        {
                            Id = 164,
                            DepartmentId = 4,
                            FirstName = "Noah",
                            LastName = "Baumbach",
                            ManagerId = 9,
                            Salary = 5050m
                        },
                        new
                        {
                            Id = 165,
                            DepartmentId = 4,
                            FirstName = "David",
                            LastName = "Lynch",
                            ManagerId = 7,
                            Salary = 5400m
                        },
                        new
                        {
                            Id = 166,
                            DepartmentId = 5,
                            FirstName = "Stephen",
                            LastName = "King",
                            ManagerId = 9,
                            Salary = 5800m
                        },
                        new
                        {
                            Id = 167,
                            DepartmentId = 5,
                            FirstName = "Mark",
                            LastName = "Twain",
                            ManagerId = 1,
                            Salary = 5600m
                        },
                        new
                        {
                            Id = 168,
                            DepartmentId = 5,
                            FirstName = "Edgar",
                            LastName = "Allan",
                            ManagerId = 9,
                            Salary = 5400m
                        },
                        new
                        {
                            Id = 169,
                            DepartmentId = 5,
                            FirstName = "Walt",
                            LastName = "Whitman",
                            ManagerId = 9,
                            Salary = 5200m
                        },
                        new
                        {
                            Id = 170,
                            DepartmentId = 5,
                            FirstName = "Herman",
                            LastName = "Melville",
                            ManagerId = 5,
                            Salary = 5100m
                        },
                        new
                        {
                            Id = 171,
                            DepartmentId = 5,
                            FirstName = "Nathaniel",
                            LastName = "Hawthorne",
                            ManagerId = 7,
                            Salary = 5050m
                        },
                        new
                        {
                            Id = 172,
                            DepartmentId = 5,
                            FirstName = "Sylvia",
                            LastName = "Plath",
                            ManagerId = 1,
                            Salary = 4750m
                        },
                        new
                        {
                            Id = 173,
                            DepartmentId = 5,
                            FirstName = "Emily",
                            LastName = "Dickinson",
                            ManagerId = 5,
                            Salary = 4800m
                        },
                        new
                        {
                            Id = 174,
                            DepartmentId = 5,
                            FirstName = "Louisa",
                            LastName = "Alcott",
                            ManagerId = 7,
                            Salary = 4650m
                        },
                        new
                        {
                            Id = 175,
                            DepartmentId = 5,
                            FirstName = "Harper",
                            LastName = "Lee",
                            ManagerId = 1,
                            Salary = 4900m
                        },
                        new
                        {
                            Id = 176,
                            DepartmentId = 5,
                            FirstName = "Jack",
                            LastName = "Kerouac",
                            ManagerId = 9,
                            Salary = 5000m
                        },
                        new
                        {
                            Id = 177,
                            DepartmentId = 5,
                            FirstName = "Allen",
                            LastName = "Ginsberg",
                            ManagerId = 5,
                            Salary = 4850m
                        },
                        new
                        {
                            Id = 178,
                            DepartmentId = 5,
                            FirstName = "Tracy",
                            LastName = "McGrady",
                            ManagerId = 7,
                            Salary = 5200m
                        },
                        new
                        {
                            Id = 179,
                            DepartmentId = 5,
                            FirstName = "Reggie",
                            LastName = "Miller",
                            ManagerId = 1,
                            Salary = 5150m
                        },
                        new
                        {
                            Id = 180,
                            DepartmentId = 5,
                            FirstName = "Patrick",
                            LastName = "Ewing",
                            ManagerId = 9,
                            Salary = 5250m
                        },
                        new
                        {
                            Id = 181,
                            DepartmentId = 5,
                            FirstName = "Karl",
                            LastName = "Malone",
                            ManagerId = 5,
                            Salary = 5300m
                        },
                        new
                        {
                            Id = 182,
                            DepartmentId = 5,
                            FirstName = "John",
                            LastName = "Stockton",
                            ManagerId = 7,
                            Salary = 5200m
                        },
                        new
                        {
                            Id = 183,
                            DepartmentId = 5,
                            FirstName = "Hakeem",
                            LastName = "Olajuwon",
                            ManagerId = 1,
                            Salary = 5450m
                        },
                        new
                        {
                            Id = 184,
                            DepartmentId = 5,
                            FirstName = "Tim",
                            LastName = "Duncan",
                            ManagerId = 9,
                            Salary = 5550m
                        },
                        new
                        {
                            Id = 185,
                            DepartmentId = 5,
                            FirstName = "Dirk",
                            LastName = "Nowitzki",
                            ManagerId = 5,
                            Salary = 5400m
                        },
                        new
                        {
                            Id = 186,
                            DepartmentId = 5,
                            FirstName = "Dwyane",
                            LastName = "Wade",
                            ManagerId = 7,
                            Salary = 5450m
                        },
                        new
                        {
                            Id = 187,
                            DepartmentId = 5,
                            FirstName = "Chris",
                            LastName = "Paul",
                            ManagerId = 1,
                            Salary = 5350m
                        },
                        new
                        {
                            Id = 188,
                            DepartmentId = 5,
                            FirstName = "Klay",
                            LastName = "Thompson",
                            ManagerId = 9,
                            Salary = 5400m
                        },
                        new
                        {
                            Id = 189,
                            DepartmentId = 5,
                            FirstName = "Draymond",
                            LastName = "Green",
                            ManagerId = 5,
                            Salary = 5200m
                        },
                        new
                        {
                            Id = 190,
                            DepartmentId = 5,
                            FirstName = "Devin",
                            LastName = "Booker",
                            ManagerId = 7,
                            Salary = 5150m
                        },
                        new
                        {
                            Id = 191,
                            DepartmentId = 5,
                            FirstName = "Jayson",
                            LastName = "Tatum",
                            ManagerId = 1,
                            Salary = 5350m
                        },
                        new
                        {
                            Id = 192,
                            DepartmentId = 5,
                            FirstName = "Jaylen",
                            LastName = "Brown",
                            ManagerId = 9,
                            Salary = 5200m
                        },
                        new
                        {
                            Id = 193,
                            DepartmentId = 5,
                            FirstName = "Nikola",
                            LastName = "Jokic",
                            ManagerId = 5,
                            Salary = 5900m
                        },
                        new
                        {
                            Id = 194,
                            DepartmentId = 5,
                            FirstName = "Luka",
                            LastName = "Doncic",
                            ManagerId = 7,
                            Salary = 5850m
                        },
                        new
                        {
                            Id = 195,
                            DepartmentId = 5,
                            FirstName = "Jimmy",
                            LastName = "Butler",
                            ManagerId = 1,
                            Salary = 5450m
                        },
                        new
                        {
                            Id = 196,
                            DepartmentId = 5,
                            FirstName = "Kyrie",
                            LastName = "Irving",
                            ManagerId = 9,
                            Salary = 5550m
                        },
                        new
                        {
                            Id = 197,
                            DepartmentId = 5,
                            FirstName = "Paul",
                            LastName = "George",
                            ManagerId = 5,
                            Salary = 5400m
                        },
                        new
                        {
                            Id = 198,
                            DepartmentId = 5,
                            FirstName = "Kemba",
                            LastName = "Walker",
                            ManagerId = 7,
                            Salary = 5100m
                        },
                        new
                        {
                            Id = 199,
                            DepartmentId = 5,
                            FirstName = "Zion",
                            LastName = "Williamson",
                            ManagerId = 1,
                            Salary = 5600m
                        },
                        new
                        {
                            Id = 200,
                            DepartmentId = 5,
                            FirstName = "Ja",
                            LastName = "Morant",
                            ManagerId = 9,
                            Salary = 5450m
                        });
                });

            modelBuilder.Entity("back_test_project.Models.Employee", b =>
                {
                    b.HasOne("back_test_project.Models.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("back_test_project.Models.Employee", "Manager")
                        .WithMany("Subordinates")
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Department");

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("back_test_project.Models.Department", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("back_test_project.Models.Employee", b =>
                {
                    b.Navigation("Subordinates");
                });
#pragma warning restore 612, 618
        }
    }
}
